services:
  etebase:
    image: laura7089/etesync
    volumes:
      - "etebase-static:/srv/etebase-server"
      - "etebase-data:/var/etebase-server"
    restart: unless-stopped

  proxy:
    depends_on: ["etebase"]
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - "etebase-static:/srv/etebase-server:ro"
      - "./etebase_nginx.conf:/etc/nginx/nginx.conf"
    restart: unless-stopped

volumes:
  etebase-static:
  etebase-data:
