services:
  etebase:
    image: laura7089/etesync
    volumes:
      - "etebase-static:/srv/etebase-server"
      - "etebase-data:/var/etebase-server"

  proxy:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - "etebase-static:/srv/etebase-server:ro"
      - "./etebase_nginx.conf:/etc/nginx/sites-available/etebase_nginx.conf:ro"

volumes:
  etebase-static:
  etebase-data:
